import Motors from '../assets/categoryIcons/picture/white-car-in-orange-background.jpg';
import Electronics from '../assets/categoryIcons/picture/electronics-in grey-background.jpg';
import Furniture from '../assets/categoryIcons/picture/furniture-on-brown-background.jpg';
import PropertySale from '../assets/categoryIcons/picture/House-in-Africa.jpg';
import MobileDevices from '../assets/categoryIcons/picture/mobile-devices.jpg'

export const categories = [
  { id: 1, name: "Motors", image: Motors, },
  { id: 2, name: "Electronics", image: Electronics, },
  { id: 3, name: 'Furniture & Interior', image: Furniture,},
  { id: 4, name: 'Property for Sale', image: PropertySale,},
  { id: 5, name: 'Mobile Devices', image: MobileDevices,},
  // ... other categories ...
];

export const subcategories = [
  { id: 1, name: "Cars", categoryId: 1 },
  { id: 2, name: "Motorcycles", categoryId: 1 },
  { id: 3, name: "Boats", categoryId: 1 },
  { id: 4, name: "Tuktuk", categoryId: 1 },

  { id: 5, name: "Computers", categoryId: 2 },
  { id: 6, name: "Home Appliances", categoryId: 2 },
  { id: 7, name: "Photo and Video", categoryId: 2 },
  { id: 8, name: "Gaming", categoryId: 2 },
  { id: 9, name: "Televisions", categoryId: 2 },
  { id: 10, name: "Audio", categoryId: 2 },

  { id: 11, name: "Bedroom", categoryId: 3 },
  // ... other subcategories ...
];

export const subsubcategories = [
  // If you have subsubcategories, they would go here
  { id: 1,name: "Sportsbike", categoryId: 1, subcategoryId: 2 },
  { id: 2, name: "Scooter", categoryId: 1, subcategoryId: 2 },
  { id: 3, name: "Moped", categoryId: 1, subcategoryId: 2 },

  { id: 4,name: "Sailboat", categoryId: 1, subcategoryId: 3 },
  { id: 5, name: "Motorboat", categoryId: 1, subcategoryId: 3 },
  { id: 6, name: "Kayak", categoryId: 1, subcategoryId: 3 },
  { id: 7, name: "Canoe", categoryId: 1, subcategoryId: 3 },

  { id: 8, name: "White Goods", categoryId: 2, subcategoryId: 6 },
  { id: 9, name: "Small Appliances", categoryId: 2, subcategoryId: 6 },
  { id: 10, name: "Desktop", categoryId: 2, subcategoryId: 5 },
  { id: 11, name: "Laptop", categoryId: 2, subcategoryId: 5 },
];

export const products = [
  {
    id: 1,
    location: "Bergen",
    distance: 312,
    year: 2017,
    title: "Nice barely used car with low milage for sale",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRa-kDjZhdHdysMISh1rIvgf4fyQE9fIzGsKoKmZWIJvwuNlyGjqMEHn7mxoymZT25LjEo&usqp=CAU",
    price: 25000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 4,
    tags: "Premium",
    model: "X3",
    make: "BMW",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 1,
    subsubcategoryId: null,
  },
  {
    id: 2,
    location: "Oslo",
    distance: 52,
    year: 2019,
    title: "Nice barely used car with low milage for sale",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXA9pxEbTwsCrkej9UbCo2V0YAtC2_-CehuCCcFpD_7bC8yk1G-IG6G3_D4DnWoPgr6a0&usqp=CAU",
    price: 545000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 5,
    tags: "Premium",
    model: "R8",
    make: "Audi",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 1,
    subsubcategoryId: null,
  },
  {
    id: 3,
    location: "Stavanger",
    distance: 125,
    year: 2020,
    title: "Nice barely used car with low milage for sale",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrxsl2yv5207GigYvrKXpCNirVO3pDqI1h7UaHWYC9i1ZpH50ovtvCY91kvmxJjylxvU8&usqp=CAU",
    price: 2500000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 5,
    tags: "Premium",
    model: "G4",
    make: "Hyundai",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 1,
    subsubcategoryId: null,
  },
  {
    id: 4,
    location: "Ålesund",
    distance: 278,
    year: 2012,
    title: "Nice barely used car with low milage for sale",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEWVGzMIfMHw9h9gCxMVouRxC7sRKmo4n24gshnO-qjKvlcXJRuF_mGDMcb4t4Bwc6b7w&usqp=CAU",
    price: 15000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 4,
    tags: "Premium",
    model: "Corolla",
    make: "Toyota",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 1,
    subsubcategoryId: null,
  },
  {
    id: 5,
    location: "Bergen",
    distance: 212,
    year: 2007,
    title: "Nice barely used car with low milage for sale",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9SoeqALksRwPxRcj_Cru3uZbSaS3JN0bsnAFVlsOcw5bRVVF2y4knL64-l_EIGK4-SAc&usqp=CAU",
    price: 40000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 4,
    tags: "Premium",
    model: "Benz",
    make: "Mercedes",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 1,
    subsubcategoryId: null,
  },
  {
    id: 6,
    location: "Tromsø",
    distance: 112,
    year: 2010,
    title: "Nice barely used tuktuk with low milage for sale",
    img: "https://cdn.fleetnews.co.uk/web-clean/1/root/new-tuk-tuks-provide-additional-support_w268.jpg",
    price: 12000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 2,
    tags: "Premium",
    model: "S8",
    make: "Tuk Tuk",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 2,
    subsubcategoryId: null,
  },
  {
    id: 7,
    location: "Trondheim",
    distance: 141,
    year: 2009,
    title: "Nice barely used tuktuk with low milage for sale",
    img: "https://cdn.pixabay.com/photo/2016/09/04/12/09/tuktuk-1643802__340.jpg",
    price: 9000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 2,
    tags: "Premium",
    model: "S4",
    make: "Tuk Tuk",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 2,
    subsubcategoryId: null,
  },
  {
    id: 8,
    location: "Hargeysa",
    title: "Gaming PC with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 250000,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2022-05-26",
    categoryId: 2,
    subcategoryId: 5,
    subsubcategoryId: 10,
  },
  {
    id: 9,
    location: "Xamar",
    title: "Gaming Laptop with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 25,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2023-04-16",
    categoryId: 2,
    subcategoryId: 5,
    subsubcategoryId: 11,
  },
  {
    id: 10,
    location: "Bosaso",
    title: "Gaming PC with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 200,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2021-07-07",
    categoryId: 2,
    subcategoryId: 5,
    subsubcategoryId: 10,
  },
  {
    id: 11,
    location: "Galkayo",
    title: "Gaming PC with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 14000,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2022-05-20",
    categoryId: 2,
    subcategoryId: 5,
    subsubcategoryId: 10,
  },
  {
    id: 12,
    location: "Burco",
    title: "Gaming Laptop with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 2000,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2023-04-12",
    categoryId: 2,
    subcategoryId: 5,
    subsubcategoryId: 11,
  },
  {
    id: 13,
    location: "Baidoa",
    title: "Gaming PC with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 5000,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2020-08-16",
    categoryId: 2,
    subcategoryId: 5,
    subsubcategoryId: 10,
  },
  {
    id: 14,
    location: "Dhuusamareeb",
    title: "Gaming Laptop with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 37000,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2023-12-17",
    categoryId: 2,
    subcategoryId: 5,
    subsubcategoryId: 11,
  },
];
