export const categories = [
  { id: 1, name: "Motors" },
  { id: 2, name: "Electronics" },
  // ... other categories ...
];

export const subcategories = [
  { id: 1, name: "Cars", categoryId: 1 },
  { id: 2, name: "Tuktuk", categoryId: 1 },
  { id: 3, name: "Computers", categoryId: 2 },
  // ... other subcategories ...
];

export const subsubcategories = [
  // If you have subsubcategories, they would go here
  { id: 1, name: "Desktop", categoryId: 2, subcategoryId: 3 },
  { id: 2, name: "Laptop", categoryId: 2, subcategoryId: 3 },
];

export const products = [
  {
    id: 1,
    location: "Bergen",
    distance: 312,
    year: 2017,
    img: "https://images.pexels.com/photos/1805053/pexels-photo-1805053.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 25000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 4,
    tags: "Premium",
    model: "X3",
    make: "BMW",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 1,
    subsubcategoryId: null,
  },
  {
    id: 2,
    location: "Oslo",
    distance: 52,
    year: 2019,
    img: "https://images.pexels.com/photos/1164778/pexels-photo-1164778.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 545000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 5,
    tags: "Premium",
    model: "R8",
    make: "Audi",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 1,
    subsubcategoryId: null,
  },
  {
    id: 3,
    location: "Stavanger",
    distance: 125,
    year: 2020,
    img: "https://images.pexels.com/photos/1519192/pexels-photo-1519192.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 2500000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 5,
    tags: "Premium",
    model: "G4",
    make: "Hyundai",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 1,
    subsubcategoryId: null,
  },
  {
    id: 4,
    location: "Ålesund",
    distance: 278,
    year: 2012,
    img: "https://images.pexels.com/photos/376361/pexels-photo-376361.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 15000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 4,
    tags: "Premium",
    model: "Corolla",
    make: "Toyota",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 1,
    subsubcategoryId: null,
  },
  {
    id: 5,
    location: "Bergen",
    distance: 212,
    year: 2007,
    img: "https://images.pexels.com/photos/3156482/pexels-photo-3156482.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 40000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 4,
    tags: "Premium",
    model: "Benz",
    make: "Mercedes",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 1,
    subsubcategoryId: null,
  },
  {
    id: 6,
    location: "Tromsø",
    distance: 112,
    year: 2010,
    img: "https://cdn.fleetnews.co.uk/web-clean/1/root/new-tuk-tuks-provide-additional-support_w268.jpg",
    price: 12000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 2,
    tags: "Premium",
    model: "S8",
    make: "Tuk Tuk",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 2,
    subsubcategoryId: null,
  },
  {
    id: 7,
    location: "Trondheim",
    distance: 141,
    year: 2009,
    img: "https://cdn.pixabay.com/photo/2016/09/04/12/09/tuktuk-1643802__340.jpg",
    price: 9000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 2,
    tags: "Premium",
    model: "S4",
    make: "Tuk Tuk",
    user: "mamo",
    date: "2022-05-26",
    color: "red",
    categoryId: 1,
    subcategoryId: 2,
    subsubcategoryId: null,
  },
  {
    id: 8,
    location: "Hargeysa",
    title: "Gaming PC with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 250000,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2022-05-26",
    categoryId: 2,
    subcategoryId: 3,
    subsubcategoryId: 1,
  },
  {
    id: 9,
    location: "Xamar",
    title: "Gaming PC with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 25,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2023-04-16",
    categoryId: 2,
    subcategoryId: 3,
    subsubcategoryId: 1,
  },
  {
    id: 10,
    location: "Bosaso",
    title: "Gaming PC with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 200,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2021-07-07",
    categoryId: 2,
    subcategoryId: 3,
    subsubcategoryId: 2,
  },
  {
    id: 11,
    location: "Galkayo",
    title: "Gaming PC with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 14000,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2022-05-20",
    categoryId: 2,
    subcategoryId: 3,
    subsubcategoryId: 1,
  },
  {
    id: 12,
    location: "Burco",
    title: "Gaming PC with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 2000,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2023-04-12",
    categoryId: 2,
    subcategoryId: 3,
    subsubcategoryId: 2,
  },
  {
    id: 13,
    location: "Baidoa",
    title: "Gaming PC with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 5000,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2020-08-16",
    categoryId: 2,
    subcategoryId: 3,
    subsubcategoryId: 2,
  },
  {
    id: 14,
    location: "Dhuusamareeb",
    title: "Gaming PC with powerful specs for sale",
    img: "https://www.ubuy.co.no/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNzFTTlhPU1ZJNkwuX0FDX1NMMTUwMF8uanBn.jpg",
    price: 37000,
    description:
      "A nice Computer, very fast with a 4010 ti and and intel i12, and 32GB ram, what a steal!",
    usage: "Slightly Used",
    condition: "Poor",
    user: "mamo",
    date: "2023-12-17",
    categoryId: 2,
    subcategoryId: 3,
    subsubcategoryId: 2,
  },
];
