export const products = [
  {
    location: "Bergen",
    distance: 312,
    year: 2017,
    img: "https://images.pexels.com/photos/1805053/pexels-photo-1805053.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 25000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 4,
    tags: "Premium",
    model: "X3",
    make: "BMW",
    user: "mamo",
    color: "red",
  },
  {
    location: "Oslo",
    distance: 52,
    year: 2019,
    img: "https://images.pexels.com/photos/1164778/pexels-photo-1164778.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 545000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 5,
    tags: "Premium",
    model: "R8",
    make: "Audi",
    user: "mamo",
    color: "red",
  },
  {
    location: "Stavanger",
    distance: 125,
    year: 2020,
    img: "https://images.pexels.com/photos/1519192/pexels-photo-1519192.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 2500000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 5,
    tags: "Premium",
    model: "G4",
    make: "Hyundai",
    user: "mamo",
    color: "red",
  },
  {
    location: "Ålesund",
    distance: 278,
    year: 2012,
    img: "https://images.pexels.com/photos/376361/pexels-photo-376361.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 15000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 4,
    tags: "Premium",
    model: "Corolla",
    make: "Toyota",
    user: "mamo",
    color: "red",
  },
  {
    location: "Bergen",
    distance: 212,
    year: 2007,
    img: "https://images.pexels.com/photos/3156482/pexels-photo-3156482.jpeg?auto=compress&cs=tinysrgb&w=1600",
    price: 40000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 4,
    tags: "Premium",
    model: "Benz",
    make: "Mercedes",
    user: "mamo",
    color: "red",
  },
  {
    location: "Tromsø",
    distance: 112,
    year: 2010,
    img: "https://cdn.fleetnews.co.uk/web-clean/1/root/new-tuk-tuks-provide-additional-support_w268.jpg",
    price: 12000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 2,
    tags: "Premium",
    model: "S8",
    make: "Tuk Tuk",
    user: "mamo",
    color: "red",
  },
  {
    location: "Trondheim",
    distance: 141,
    year: 2009,
    img: "https://cdn.pixabay.com/photo/2016/09/04/12/09/tuktuk-1643802__340.jpg",
    price: 9000,
    description:
      "a very nice car, must buy, great deal, BUY IT! NOOOW! or go to jail",
    doors: 2,
    tags: "Premium",
    model: "S4",
    make: "Tuk Tuk",
    user: "mamo",
    color: "red",
  },
];