name: AI Code Review
on: pull_request

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: mamo-00/Code-Patrol/.github/actions/action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
